[package]
name = "linux_ipc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.203", features = ["derive"] }
